services:

  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: ibkr_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
      - ./config:/app/config:ro
    restart: unless-stopped

  etl:
    build: 
      context: .
      dockerfile: Dockerfile.etl
    container_name: ibkr_etl
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - ./config:/app/config
    command: python main.py --job polygon-bars --schedule
    restart: unless-stopped
    depends_on:
      - dashboard
